src/components/loginPage/Login.jsx
src/components/menuBar/MenuBar.jsx

로그인하기 퍼블리싱 값 수정
메뉴바는 지속적으로 사용하기 위해 컴포넌트로 분리 후 기초 작업

로그인하기 퍼블리싱 수정, 메뉴바 컴포넌트로 분리 후 기초 작업

---

package-lock.json
package.json
src/components/loginPage/Find.jsx
src/components/loginPage/FindEnd.jsx

아이디/비밀번호 찾기 페이지 작업

---

src/components/loginPage/Find.jsx

풀페이지에 맞춰 스타일 작업.
헤더 사용자 정보 주석처리

정보찾기 페이지 작업

---

src/components/0.menuBar/MenuBar.jsx

메뉴 컴포넌트 홈버튼 하버, 클릭 수정

---

src/components/0.menuBar/MenuBar.jsx

하단 메뉴바 수정완료

---

src/components/loginPage/Find.jsx
src/components/loginPage/FindEnd.jsx

아이디 찾기 후, 로그인 페이지 이동
새로운 비밀번호 설정
비밀번호 조건으로 동일한 값이여만 버튼 누르게 수정

아이디 비밀번호 찾기 완료 페이지

---

package-lock.json
package.json
src/components/loginPage/SignUp.jsx

아이디 이메일 문자 한정 팝업
아이디 중복값 모달 수정

회원가입 페이지 수정

---

src/App.js
src/components/myPage/MyPage.jsx

마이페이지 제작시작, 영역잡기

---

src/App.js
src/components/0.menuBar/MenuBar.jsx
src/components/myPage/MyPage.jsx

마이페이지 퍼블리싱 완료 / 메뉴바 클릭시 마이페이지로 링크

마이페이지 퍼블리싱 완료 / 메뉴바 클릭시 마이페이지로 링크

---

src/App.js
src/components/loginPage/SignUp.jsx
src/components/loginPage/SignUpComplete.jsx

로그인할때 이미지 추가해서 로그인하는경우 구현

---

src/components/loadingItem/Loading.jsx
src/components/modal/MyPageProfile.jsx
src/components/myPage/MyPage.jsx

마이페이지 + 마이페이지 프로필 편집 모달창 하드코딩 완료

마이페이지 + 마이페이지 프로필 편집 모달창 하드코딩 완료

---

src/components/1.searchPage/SearchMain.jsx
src/components/MainContainer.jsx
src/components/loginPage/Login.jsx
src/components/loginPage/login_kakao.js
src/components/modal/MainModalInfoWindow.jsx
src/components/modal/MainModalPlace.jsx
src/features/member/memberSlice.js

지도에 지역으로 검색 시 결과값 나옴! 모달로 구현함 -> 이미지가 포털에 검색되어서 나오는 구조로 구현함

지역으로 검색 시 관광명소 나옴(저장x) 모달창으로 해당 정보 구현

---

src/components/modal/LoginNeed.jsx

현재 비회원 페이지가 안나와있어서 클로즈 버튼은 만들지 않았음.
백그라운드 컬러는 오퍼시티 조절 해놔서 바로 사용가능

로그인이 필요합니다 모달창 작업완료

---

src/App.js
src/components/menuBar/MyTravelList.jsx
src/components/menuBar/MyTravelListDetail.jsx

나의여행상세페이지 작업

---

src/App.js
src/components/0.menuBar/MenuBar.jsx
src/components/menuBar/Lookaround.jsx

둘러보기 페이지 작업

---

src/components/modal/MyPageProfile.jsx
src/components/myPage/MyPage.jsx
src/features/member/memberSlice.js

이름, 이메일주소 받아오고 뿌려주기 + 회원가입일로부터 디데이 표시

이름, 이메일주소 받아오고 뿌려주기 + 회원가입일로부터 디데이 표시

---

src/components/1.searchPage/SearchMainResult.jsx

searchMainResult

---

src/api/member/member_localstorage.js
src/components/loginPage/Login.jsx
src/components/modal/MyPageProfile.jsx
src/components/myPage/MyPage.jsx
src/features/member/memberSlice.js

마이페이지 수정하기 버튼 클릭시 수정하기 (최종X)

---

src/components/loginPage/SignUp.jsx
src/components/modal/MyPageProfile.jsx

회원가입 닉네임, 번호, 생일 추가

---

src/api/map/map-result.js
src/components/0.menuBar/Header.jsx
src/components/0.menuBar/MenuBar.jsx
src/components/1.searchPage/SearchMain.jsx
src/components/1.searchPage/SearchMainResult.jsx
src/components/MainContainer.jsx
src/components/modal/MainModalInfoWindow.jsx

메인페이지에서 로그인 상태 유지하게 만듬 (로컬스토리지 이용)

소트정리 css수정..

---

src/api/landmarkComment/landmarkComment.js

landmarkcomment

---

src/components/loginPage/SignUp.jsx
src/components/modal/MyPageProfile.jsx
src/components/myPage/MyPage.jsx

플로필 편집 수정하기 클릭시 아이디를 제외한 전부 수정 가능

플로필 편집 수정하기 클릭시 아이디를 제외한 전부 수정 가능

---

src/components/subpage/Comments.jsx

uuid 사용
게시 Btn
수정,삭제 Btn 만들기 완료.
대댓기능은 추가 XX
index.js에서 확인해봤음.

subpage폴더 추가 후,Comments 컴포넌트 작업 완료

---

src/components/loginPage/SignUp.jsx
src/components/modal/MyPageProfile.jsx
src/features/member/memberSlice.js

프로필편집 수정완료 아직 디비에 넣지는 않음

---

src/components/1.searchPage/SearchMainResult.jsx

사용자가 포커스가 떨어지면 값이 저장됨
사용자가 엔터를 눌러도 저장됨

텍스트 저장 값 수정

---

src/components/modal/MyPageProfile.jsx
src/components/myPage/MyPage.jsx

마이페이지 해시태그 수정하기 기능 추가

---

src/components/0.menuBar/Header.jsx
src/components/modal/MyPageProfile.jsx

마이페이지 모달창 해시태그 줄바꿈 3번 제한 둠
헤더 컴포넌트 스크롤 내리면 헤더 숨기기 올리면 다시 나타나게 수정함.

마이페이지 모달창 헤더 컴포넌트 수정

---

package-lock.json
package.json
src/components/menuBar/Clipping.jsx

스크랩 페이지 드로그앤 드롭 설정
